'use client';

import Link from 'next/link';
import { motion, useReducedMotion } from 'framer-motion';

export default function TermsPage() {
  const shouldReduceMotion = useReducedMotion();

  const sectionVariants = {
    hidden: shouldReduceMotion ? { opacity: 1 } : { opacity: 0, y: 20 },
    visible: shouldReduceMotion ? { opacity: 1 } : { opacity: 1, y: 0 },
  };

  return (
    <main className="flex min-h-screen flex-col bg-[var(--bg-home)] pt-[68px]">
      {/* Nav */}
      <div className="fixed top-0 right-0 left-0 z-50 bg-[var(--bg-home)] px-6 pt-4 pb-0">
        <nav className="mx-auto flex w-full max-w-[900px] items-center justify-between rounded-full bg-white px-4 py-2.5 pl-5 shadow-[0_2px_12px_rgba(0,0,0,0.08)]">
          <Link href="/" className="flex items-center gap-2 no-underline">
            <div className="flex h-7 w-7 items-center justify-center rounded-full bg-[#E8E815]">
              <svg width="13" height="13" viewBox="0 0 14 14" fill="none">
                <path d="M7 11V3M7 3L3.5 6.5M7 3L10.5 6.5" stroke="#0A0A0A" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>
            <span className="font-heading text-[15px] font-bold tracking-[-0.03em] text-[#0A0A0A]">Calendarito</span>
          </Link>
          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="font-heading text-sm font-medium text-[#555] hover:text-[#0A0A0A] transition-colors"
            >
              Home
            </Link>
            <Link
              href="/empezar"
              className="font-heading rounded-full bg-[#0A0A0A] px-5 py-2 text-sm font-semibold text-white no-underline transition-colors hover:bg-[#333]"
            >
              Start
            </Link>
          </div>
        </nav>
      </div>

      <div className="mx-auto max-w-3xl px-6 py-16">
        <motion.div
          initial="hidden"
          animate="visible"
          variants={sectionVariants}
          transition={{ duration: shouldReduceMotion ? 0 : 0.4 }}
          className="mb-12"
        >
          <h1 className="font-heading text-5xl font-bold tracking-[-0.04em] text-[#0A0A0A]">
            Terms of Service
          </h1>
          <p className="mt-4 text-lg text-[#555]">
            Last updated: April 8, 2026
          </p>
          <p className="mt-2 text-sm text-[#888]">
            Please read these Terms of Service carefully before using Calendarito. By accessing or using the Service — including signing in with Google, submitting content, or creating calendar events — you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>
        </motion.div>

        <div className="prose prose-neutral max-w-none prose-headings:font-heading prose-headings:tracking-[-0.02em] prose-headings:font-semibold">

          {/* 1 — Introduction & Definitions */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">1. Introduction &amp; Key Definitions</h2>
          <p className="text-[15px] text-[#444] leading-relaxed">
            These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and Calendarito ("Calendarito," "we," "us," or "our") governing your access to and use of the Calendarito web application and any related services (collectively, the "Service"). <strong>By signing in with Google, submitting content, or clicking any confirmation button in the Service, you affirmatively accept these Terms.</strong> If you do not agree, you must not use the Service.
          </p>
          <p className="text-[15px] text-[#444] leading-relaxed mt-3">
            These Terms incorporate our{' '}
            <Link href="/privacy" className="text-[#0A0A0A] underline">Privacy Policy</Link>
            {' '}by reference; the Privacy Policy is part of this agreement. In the event of a conflict between these Terms and the Privacy Policy on data handling matters, the Privacy Policy controls. All data practices are governed exclusively by the Privacy Policy.
          </p>

          <div className="mt-6 rounded-xl border border-[#E8E8E8] p-5 text-[14px] text-[#555] space-y-2">
            <p><strong className="text-[#0A0A0A]">"Service"</strong> — The Calendarito web application, including all features, AI extraction functionality, and Google Calendar integration.</p>
            <p><strong className="text-[#0A0A0A]">"User Content"</strong> — Any text, files, PDFs, images, or other material you submit to the Service for event extraction.</p>
            <p><strong className="text-[#0A0A0A]">"Extracted Events"</strong> — The structured calendar event data (title, date, time, location, description) generated by the AI from your User Content.</p>
            <p><strong className="text-[#0A0A0A]">"Google Calendar"</strong> — The Google Calendar service operated by Google LLC, accessed through the Google Calendar API on your behalf using your OAuth credentials.</p>
            <p><strong className="text-[#0A0A0A]">"AI Output"</strong> — Any Extracted Event or other result generated by the AI model from your User Content. AI Output is a suggestion only and not a guarantee of accuracy.</p>
          </div>

          {/* 2 — Description of Service */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">2. Description of Service</h2>
          <p className="text-[15px] text-[#444] leading-relaxed">
            Calendarito is a web application that helps you create Google Calendar events by extracting structured event data from text, files, PDFs, and images using AI (currently OpenAI gpt-4o). The Service operates as follows:
          </p>
          <ul className="mt-4 space-y-3 text-[15px] text-[#444]">
            <li className="flex items-start gap-3">• You authenticate via Google OAuth, granting Calendarito limited permission to create events in your Google Calendar.</li>
            <li className="flex items-start gap-3">• You submit User Content; the AI processes it transiently and returns Extracted Events for your review.</li>
            <li className="flex items-start gap-3">• You explicitly confirm which events to create — <strong>nothing is added to your calendar without your affirmative action.</strong></li>
            <li className="flex items-start gap-3">• User Content and Extracted Events are not stored on our servers beyond the in-flight processing session. See our{' '}<Link href="/privacy" className="text-[#0A0A0A] underline">Privacy Policy</Link> for full data handling details.</li>
          </ul>
          <p className="mt-4 text-[15px] text-[#444]">
            We grant you a limited, non-exclusive, non-transferable, revocable license to use the Service for personal, non-commercial purposes, subject to these Terms.
          </p>

          {/* 3 — Eligibility & Accounts */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">3. Eligibility &amp; User Accounts</h2>
          <p className="text-[15px] text-[#444]">
            To use the Service you must:
          </p>
          <ul className="mt-4 space-y-3 text-[15px] text-[#444]">
            <li className="flex items-start gap-3">• Be at least 13 years of age. <strong>Children under 13 may not use the Service under any circumstances.</strong> If you are between 13 and 17, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf.</li>
            <li className="flex items-start gap-3">• Have a valid Google account and agree to Google&apos;s Terms of Service.</li>
            <li className="flex items-start gap-3">• Have the legal capacity to enter into a binding agreement in your jurisdiction.</li>
          </ul>
          <p className="mt-4 text-[15px] text-[#444]">
            Account access is managed exclusively through Google OAuth. You are responsible for maintaining the security of your Google account and for all activity that occurs under your account. Do not share your Google credentials or allow others to use your Calendarito session. Notify us immediately at{' '}
            <a href="mailto:privacy@calendarito.com" className="text-[#0A0A0A] underline">privacy@calendarito.com</a>{' '}
            if you believe your account has been compromised.
          </p>

          {/* 4 — User Content & Responsibilities */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">4. User Content &amp; Acceptable Use</h2>
          <p className="text-[15px] text-[#444]">
            <strong>You retain ownership of your User Content.</strong> By submitting User Content to the Service, you grant us a limited, non-exclusive, royalty-free, transient license to process it solely for the purpose of generating Extracted Events during your active session. This license terminates immediately after processing completes; we do not store, reproduce, or use your User Content for any other purpose.
          </p>

          <h3 className="mt-6 text-lg font-semibold text-[#0A0A0A]">You represent and warrant that:</h3>
          <ul className="mt-3 space-y-3 text-[15px] text-[#444]">
            <li className="flex items-start gap-3">• You own or have the necessary rights to submit any content you provide to the Service.</li>
            <li className="flex items-start gap-3">• Your User Content does not violate any applicable law or the rights of any third party (including intellectual property, privacy, or confidentiality rights).</li>
            <li className="flex items-start gap-3">• You are solely responsible for the accuracy of the events created in your Google Calendar and any consequences arising from them (including missed or incorrect appointments).</li>
          </ul>

          <h3 className="mt-6 text-lg font-semibold text-[#0A0A0A]">Prohibited uses. You may not:</h3>
          <ul className="mt-3 space-y-3 text-[15px] text-[#444]">
            <li className="flex items-start gap-3">• Submit illegal, infringing, defamatory, harassing, or otherwise unlawful content.</li>
            <li className="flex items-start gap-3">• Use the Service to process content belonging to third parties without authorization.</li>
            <li className="flex items-start gap-3">• Attempt to reverse engineer, decompile, scrape, or extract the Service&apos;s underlying code, models, or AI outputs for purposes other than personal use.</li>
            <li className="flex items-start gap-3">• Use Extracted Events or any Service outputs to train, fine-tune, or evaluate any AI or machine learning model.</li>
            <li className="flex items-start gap-3">• Use the Service in a manner that could overload, damage, or impair our infrastructure or Google&apos;s or OpenAI&apos;s systems.</li>
            <li className="flex items-start gap-3">• Access the Service through automated scripts, bots, or crawlers without our prior written consent.</li>
            <li className="flex items-start gap-3">• Use the Service for any commercial purpose, resale, or competitive intelligence without our prior written consent.</li>
            <li className="flex items-start gap-3">• Use the Service as the sole or primary basis for high-stakes decisions — including medical, legal, financial, or safety-critical scheduling — without independent verification. AI Output is a drafting aid, not a reliable source of truth for consequential matters.</li>
          </ul>

          {/* 5 — AI Features & Disclaimers */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">5. AI Features &amp; Accuracy Disclaimer</h2>
          <p className="text-[15px] text-[#444]">
            The event extraction feature is powered by a large language model (currently OpenAI gpt-4o) and is provided as a convenience tool to help you draft calendar events. You acknowledge that:
          </p>
          <ul className="mt-4 space-y-3 text-[15px] text-[#444]">
            <li className="flex items-start gap-3">• <strong>AI outputs are suggestions only.</strong> Extracted Events may be inaccurate, incomplete, incorrectly dated, or otherwise erroneous ("hallucinations"). You must review and confirm all Extracted Events before creating them in your Google Calendar.</li>
            <li className="flex items-start gap-3">• <strong>You bear full responsibility</strong> for any calendar event created, including any consequences (missed meetings, incorrect times, double-bookings, etc.) resulting from reliance on AI output.</li>
            <li className="flex items-start gap-3">• AI outputs do not constitute professional advice of any kind (legal, medical, financial, scheduling, or otherwise).</li>
            <li className="flex items-start gap-3">• We do not use your User Content or Extracted Events to train AI models. OpenAI processes your content as a service provider under a data processing agreement that prohibits training on your data.</li>
            <li className="flex items-start gap-3">• We do not guarantee that the AI will correctly interpret every nuance of your User Content, including ambiguous language, attachments, or context-specific details.</li>
            <li className="flex items-start gap-3">• AI model behavior may change over time. We do not guarantee consistent extraction quality across model updates.</li>
          </ul>

          {/* 6 — Intellectual Property */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">6. Intellectual Property</h2>
          <p className="text-[15px] text-[#444]">
            The Service — including its code, design, user interface, branding, trademarks, and all aggregated or anonymized data derived from service operations — is the exclusive property of Calendarito and is protected by applicable intellectual property laws. Nothing in these Terms transfers any ownership rights in the Service to you.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            You may not copy, modify, distribute, sell, sublicense, or create derivative works based on the Service or any part of it without our prior written consent.
          </p>

          {/* 7 — Third-Party Services */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">7. Third-Party Services &amp; Integrations</h2>
          <p className="text-[15px] text-[#444]">
            The Service depends on third-party platforms that have their own terms and policies. By using Calendarito, you also agree to comply with:
          </p>

          <div className="mt-4 space-y-4 text-[15px]">
            <div className="rounded-xl border border-[#E8E8E8] p-5">
              <p className="font-semibold text-[#0A0A0A] mb-1">Google</p>
              <p className="text-[14px] text-[#555]">
                Your use of Google Calendar via Calendarito is subject to{' '}
                <a href="https://policies.google.com/terms" target="_blank" rel="noopener noreferrer" className="text-[#0A0A0A] underline">Google&apos;s Terms of Service</a>{' '}
                and the{' '}
                <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer" className="text-[#0A0A0A] underline">Google API Services User Data Policy</a>.
                Our use of Google API data adheres to the Limited Use requirements. We access only the <code>calendar.events</code> write scope necessary to create events you confirm. We do not read your existing calendar events or any other Google data.
              </p>
            </div>

            <div className="rounded-xl border border-[#E8E8E8] p-5">
              <p className="font-semibold text-[#0A0A0A] mb-1">OpenAI</p>
              <p className="text-[14px] text-[#555]">
                AI extraction is powered by the OpenAI API, subject to{' '}
                <a href="https://openai.com/policies/terms-of-use" target="_blank" rel="noopener noreferrer" className="text-[#0A0A0A] underline">OpenAI&apos;s Terms of Use</a>.
                OpenAI acts as a service provider and does not use your content to train models under our agreement.
              </p>
            </div>
          </div>

          <p className="mt-4 text-[15px] text-[#444]">
            We are not responsible for any outages, changes in functionality, data loss, or policy changes by Google, OpenAI, or any other third-party service. We are not liable for any harm arising from your use of those third-party platforms.
          </p>

          {/* 8 — Payments */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">8. Payments &amp; Billing</h2>
          <p className="text-[15px] text-[#444]">
            Calendarito is currently offered free of charge. We reserve the right to introduce paid plans or usage limits in the future. If we do, we will update these Terms and provide advance notice. Continued use of the Service after any new pricing takes effect constitutes your acceptance of the updated terms.
          </p>

          {/* 9 — Termination */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">9. Termination &amp; Suspension</h2>
          <p className="text-[15px] text-[#444]">
            <strong>By you:</strong> You may stop using the Service at any time. To revoke Calendarito&apos;s access to your Google account, visit your{' '}
            <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="text-[#0A0A0A] underline">Google Account permissions</a>.
            Revoking access terminates the Service&apos;s ability to interact with your Google Calendar.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>By us:</strong> We may suspend or terminate your access to the Service, without prior notice or liability, if we believe you have violated these Terms, engaged in abusive behavior, or if we are required to do so by law or a third-party platform (e.g., Google revokes our API access). Upon termination, the license granted to you under these Terms immediately ends.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            Sections 4 (User Content ownership), 5 (AI Disclaimers), 6 (Intellectual Property), 10 (Disclaimers &amp; Limitation of Liability), 11 (Indemnification), 12 (Governing Law), and 14 (Contact) survive any expiration or termination of these Terms.
          </p>

          {/* 10 — Disclaimers & Limitation of Liability */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">10. Disclaimers &amp; Limitation of Liability</h2>

          <p className="text-[15px] text-[#444] mt-4">
            <strong>The Service is provided "as is" and "as available"</strong> without warranty of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, accuracy, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that AI extractions will be accurate or complete.
          </p>
          <p className="text-[15px] text-[#444] mt-4">
            To the extent permitted by applicable law, Calendarito and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages (including lost data, missed appointments, business interruption, or loss of profits) arising out of or related to your use of the Service, even if advised of the possibility of such damages.
          </p>
          <p className="text-[15px] text-[#444] mt-4">
            To the extent permitted by applicable law, in no event shall our total liability to you for all claims exceed the greater of the amount you paid to us in the 12 months preceding the claim or one hundred U.S. dollars (USD $100). Some jurisdictions do not allow certain liability limitations; in those jurisdictions, our liability is limited to the maximum extent permitted by law.
          </p>

          {/* 11 — Indemnification */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">11. Indemnification</h2>
          <p className="text-[15px] text-[#444]">
            You agree to defend, indemnify, and hold harmless Calendarito and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable attorneys&apos; fees) arising out of or in any way connected with:
          </p>
          <ul className="mt-4 space-y-3 text-[15px] text-[#444]">
            <li className="flex items-start gap-3">• Your User Content or your use of the Service;</li>
            <li className="flex items-start gap-3">• Your violation of these Terms;</li>
            <li className="flex items-start gap-3">• Your violation of any third-party rights, including Google&apos;s or OpenAI&apos;s terms; or</li>
            <li className="flex items-start gap-3">• Any calendar events created through the Service, reliance on AI Output, and the consequences thereof.</li>
          </ul>

          {/* 12 — Governing Law & Dispute Resolution */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">12. Governing Law &amp; Dispute Resolution</h2>
          <p className="text-[15px] text-[#444]">
            These Terms are governed by the laws of the State of California, without regard to its conflict-of-law principles. Any dispute arising from or related to these Terms or the Service shall be resolved exclusively in the state or federal courts located in California, and you consent to personal jurisdiction in those courts.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>Informal resolution first:</strong> Before filing a claim, you agree to contact us at{' '}
            <a href="mailto:privacy@calendarito.com" className="text-[#0A0A0A] underline">privacy@calendarito.com</a>{' '}
            and give us 30 days to attempt to resolve the dispute informally.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>Severability:</strong> If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>Entire agreement:</strong> These Terms and the Privacy Policy constitute the entire agreement between you and Calendarito regarding the Service and supersede any prior agreements on the same subject matter.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>No waiver:</strong> Our failure to enforce any right or provision of these Terms will not be considered a waiver of that right or provision.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>No assignment:</strong> You may not assign your rights or obligations under these Terms without our prior written consent. We may assign our rights freely, including in connection with a merger, acquisition, or sale of assets.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            <strong>Export controls:</strong> You represent that you are not located in, or a national or resident of, any country subject to U.S. government embargo or designated as a "terrorist supporting" country, and that you are not listed on any U.S. government list of prohibited or restricted parties. You agree to comply with all applicable export control laws in connection with your use of the Service.
          </p>

          {/* 13 — Changes to Terms */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">13. Changes to These Terms</h2>
          <p className="text-[15px] text-[#444]">
            We may update these Terms from time to time. For material changes — those that materially affect your rights or our obligations — we will provide at least 30 days&apos; advance notice via email (to the address associated with your Google account) or a prominent in-app notification. The "Last updated" date at the top of this page reflects the most recent revision.
          </p>
          <p className="mt-4 text-[15px] text-[#444]">
            Your continued use of the Service after the effective date of updated Terms constitutes your acceptance of the changes. If you do not agree to the updated Terms, you must stop using the Service and revoke our Google access.
          </p>

          {/* 14 — Contact */}
          <h2 className="mt-12 text-2xl font-semibold text-[#0A0A0A]">14. Contact Us</h2>
          <p className="text-[15px] text-[#444]">
            For questions about these Terms, to report a violation, or for any legal notices:
          </p>
          <div className="mt-4 rounded-xl border border-[#E8E8E8] p-5 text-[14px] text-[#555] space-y-1">
            <p><strong className="text-[#0A0A0A]">Calendarito</strong></p>
            <p>
              Email:{' '}
              <a href="mailto:privacy@calendarito.com" className="text-[#0A0A0A] underline">
                privacy@calendarito.com
              </a>
            </p>
          </div>

          <div className="mt-16 border-t border-[#E0E0E0] pt-8 text-xs text-[#888]">
            <p>
              These Terms of Service should be read together with our{' '}
              <Link href="/privacy" className="text-[#0A0A0A] underline">Privacy Policy</Link>.
              Legal references: FTC Act § 5; Google API Services User Data Policy; Cal. Civ. Code §§ 1798.100 et seq. (CCPA/CPRA); general U.S. contract law.
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
